version: 2

default_workflow_jobs: &default_workflow_jobs
  - lint
  - test-latest:
      requires:
        - lint
  - test-7.1:
      requires:
        - lint
  - test-7.2:
      requires:
        - lint
  - test-7.3:
      requires:
        - lint  
  - test-7.4:
      requires:
        - lint
        
workflows:
  version: 2
  lint-test:
    jobs: *default_workflow_jobs

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run: make lint
  test-latest:
    machine: true
    steps:
      - checkout
      - run: make test-image IMAGE="php:fpm-alpine" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:fpm-buster" DOCKERFILE="buster"

  test-7.1:
    machine: true
    steps:
      - checkout
      - run: make test-image IMAGE="php:7.1-fpm-alpine3.7" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.1-fpm-alpine3.8" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.1-fpm-stretch" DOCKERFILE="stretch"

  test-7.2:
    machine: true
    steps:
      - checkout
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.7" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.8" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-stretch" DOCKERFILE="stretch"

  test-7.3:
    machine: true
    steps:
      - checkout
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.8" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.9" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.10" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.11" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-stretch" DOCKERFILE="stretch"

  test-7.4:
    machine: true
    steps:
      - checkout
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.10" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.11" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-buster" DOCKERFILE="buster"
